package nightskyataglance.gui;

/*******************************************************************************
 * Copyright (c) 2025-2025 Douglas M. Pase                                     *
 * All rights reserved.                                                        *
 * Redistribution and use in source and binary forms, with or without          *
 * modification, are permitted provided that the following conditions          *
 * are met:                                                                    *
 * o       Redistributions of source code must retain the above copyright      *
 *         notice, this list of conditions and the following disclaimer.       *
 * o       Redistributions in binary form must reproduce the above copyright   *
 *         notice, this list of conditions and the following disclaimer in     *
 *         the documentation and/or other materials provided with the          *
 *         distribution.                                                       *
 * o       Neither the name of the copyright holder nor the names of its       *
 *         contributors may be used to endorse or promote products derived     *
 *         from this software without specific prior written permission.       *
 *                                                                             *
 * The copyright holders provide no reassurances that the source code provided *
 * does not infringe any patent, copyright, or any other intellectual property *
 * rights of third parties. The copyright holders disclaim any liability to    *
 * any recipient for claims brought against recipient by any third party for   *
 * infringement of that parties intellectual property rights.                  *
 *                                                                             *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" *
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE   *
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  *
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE   *
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR         *
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF        *
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS    *
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN     *
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)     *
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF      *
 * THE POSSIBILITY OF SUCH DAMAGE.                                             *
 *******************************************************************************/


import java.io.IOException;

import lib.stars.catalog.YaleBrightStarAscCatalog;

public class ConstellationOutline {
	public static final int ANDROMEDA = 0;
	public static final String[][][][] outline = {
		{	// Andromeda
			{{"And", "alpha",   "" }, {"And", "delta",   "" }},
			{{"And", "delta",   "" }, {"And", "epsilon", "" }},
			{{"And", "epsilon", "" }, {"And", "zeta",    "" }},
			{{"And", "zeta",    "" }, {"And", "eta",     "" }},
			{{"And", "delta",   "" }, {"And", "pi",      "" }},
			{{"And", "pi",      "" }, {"And", "beta",    "" }},
			{{"And", "beta",    "" }, {"And", "delta",   "" }},
			{{"And", "pi",      "" }, {"And", "iota",    "" }},
			{{"And", "iota",    "" }, {"And", "kappa",   "" }},
			{{"And", "kappa",   "" }, {"And", "lambda",  "" }},
			{{"And", "iota",    "" }, {"And", "omicron", "" }},
			{{"And", "beta",    "" }, {"And", "upsilon", "" }},
			{{"And", "upsilon", "" }, {"And", "gamma",   "1"}},
			{{"And", "beta",    "" }, {"And", "mu",      "" }},
			{{"And", "mu",      "" }, {"And", "nu",      "" }},
			{{"And", "nu",      "" }, {"And", "phi",     "" }},
			{{"And", "phi",     "" }, {"And", "51",      "" }},
		},
		{	// Antlia
			{{"Ant", "alpha",   "" }, {"Ant", "iota",    "" }},
			{{"Ant", "alpha",   "" }, {"Ant", "theta",   "" }},
			{{"Ant", "theta",   "" }, {"Ant", "epsilon", "" }},
		},
		{	// Apus,
			{{"Aps", "alpha",   "" }, {"Aps", "delta",   "1"}},
			{{"Aps", "delta",   "1"}, {"Aps", "beta",    "" }},
			{{"Aps", "beta",    "" }, {"Aps", "gamma",   "" }},
		},
		{	// Aquarius
			{{"Aqr", "alpha",   "" }, {"Aqr", "gamma",   "" }},
			{{"Aqr", "gamma",   "" }, {"Aqr", "zeta",    "1"}},
			{{"Aqr", "zeta",    "1"}, {"Aqr", "eta",     "" }},
			{{"Aqr", "zeta",    "1"}, {"Aqr", "pi",      "" }},
			{{"Aqr", "pi",      "" }, {"Aqr", "alpha",   "" }},
			{{"Aqr", "alpha",   "" }, {"Aqr", "beta",    "" }},
			{{"Aqr", "beta",    "" }, {"Aqr", "mu",      "" }},
			{{"Aqr", "mu",      "" }, {"Aqr", "epsilon", "" }},
			{{"Aqr", "beta",    "" }, {"Aqr", "iota",    "" }},
			{{"Aqr", "alpha",   "" }, {"Aqr", "theta",   "" }},
			{{"Aqr", "theta",   "" }, {"Aqr", "lambda",  "" }},
			{{"Aqr", "lambda",  "" }, {"Aqr", "tau",     "1"}},
			{{"Aqr", "tau",     "1"}, {"Aqr", "delta",   "" }},
			{{"Aqr", "delta",   "" }, {"Aqr", "psi",     "1"}},
			{{"Aqr", "psi",     "1"}, {"Aqr", "phi",     "" }},
			{{"Aqr", "phi",     "" }, {"Aqr", "lambda",  "" }},
			{{"Aqr", "psi",     "1"}, {"Aqr", "omega",   "1"}},
		},
		{	// Aquila
			{{"Aql", "beta",    "" }, {"Aql", "alpha",   "" }},
			{{"Aql", "alpha",   "" }, {"Aql", "gamma",   "" }},
			{{"Aql", "gamma",   "" }, {"Aql", "delta",   "" }},
			{{"Aql", "delta",   "" }, {"Aql", "eta",     "" }},
			{{"Aql", "eta",     "" }, {"Aql", "theta",   "" }},
			{{"Aql", "theta",   "" }, {"Aql", "66",      "" }},
			{{"Aql", "theta",   "" }, {"Aql", "iota",    "" }},
			{{"Aql", "iota",    "" }, {"Aql", "lambda",  "" }},
			{{"Aql", "lambda",  "" }, {"Aql", "12",      "" }},
			{{"Aql", "lambda",  "" }, {"Aql", "delta",   "" }},
			{{"Aql", "lambda",  "" }, {"Aql", "zeta",    "" }},
			{{"Aql", "zeta",    "" }, {"Aql", "epsilon", "" }},
			{{"Aql", "zeta",    "" }, {"Aql", "delta",   "" }},
		},
		{	// Ara
			{{"Ara", "beta",    "" }, {"Ara", "alpha",   "" }},
			{{"Ara", "alpha",   "" }, {"Ara", "epsilon", "1"}},
			{{"Ara", "epsilon", "1"}, {"Ara", "eta",     "" }},
			{{"Ara", "zeta",    "" }, {"Ara", "eta",     "" }},
			{{"Ara", "eta",     "" }, {"Ara", "delta",   "" }},
			{{"Ara", "delta",   "" }, {"Ara", "gamma",   "" }},
		},
		{	// Aries
			{{"Ari", "alpha",   "" }, {"Ari", "beta",    "" }},
			{{"Ari", "beta",    "" }, {"Ari", "gamma",   "1"}},
			{{"Ari", "alpha",   "" }, {"Ari", "lambda",  "" }},
			{{"Ari", "alpha",   "" }, {"Ari", "33",      "" }},
			{{"Ari", "33",      "" }, {"Ari", "41",      "" }},
			{{"Ari", "alpha",   "" }, {"Ari", "nu",      "" }},
			{{"Ari", "nu",      "" }, {"Ari", "epsilon", "" }},
			{{"Ari", "epsilon", "" }, {"Ari", "zeta",    "" }},
			{{"Ari", "zeta",    "" }, {"Ari", "tau",     "1"}},
			{{"Ari", "epsilon", "" }, {"Ari", "delta",   "" }},
		},
		{	// Auriga
			{{"Aur", "alpha",   "" }, {"Aur", "beta",    "" }},
			{{"Aur", "beta",    "" }, {"Aur", "delta",   "" }},
			{{"Aur", "delta",   "" }, {"Aur", "alpha",   "" }},
			{{"Aur", "alpha",   "" }, {"Aur", "epsilon", "" }},
			{{"Aur", "epsilon", "" }, {"Aur", "zeta",    "" }},
			{{"Aur", "alpha",   "" }, {"Aur", "eta",     "" }},
			{{"Aur", "eta",     "" }, {"Aur", "iota",    "" }},
			{{"Aur", "beta",    "" }, {"Aur", "theta",   "" }},
			{{"Aur", "theta",   "" }, {"Tau", "beta",    "" }},
			{{"Aur", "iota",    "" }, {"Tau", "beta",    "" }},
		},
		{	// Bootes
			{{"Boo", "alpha",   "" }, {"Boo", "zeta",    "" }},
			{{"Boo", "alpha",   "" }, {"Boo", "eta",     "" }},
			{{"Boo", "alpha",   "" }, {"Boo", "epsilon", "" }},
			{{"Boo", "alpha",   "" }, {"Boo", "rho",     "" }},
			{{"Boo", "epsilon", "" }, {"Boo", "delta",   "" }},
			{{"Boo", "rho",     "" }, {"Boo", "gamma",   "" }},
			{{"Boo", "delta",   "" }, {"Boo", "beta",    "" }},
			{{"Boo", "gamma",   "" }, {"Boo", "beta",    "" }},
			{{"Boo", "gamma",   "" }, {"Boo", "lambda",  "" }},
			{{"Boo", "lambda",  "" }, {"Boo", "theta",   "" }},
			{{"Boo", "theta",   "" }, {"Boo", "kappa",   "1"}},
			{{"Boo", "lambda",  "" }, {"Boo", "kappa",   "1"}},
		},
		{	// Caelum
			{{"Cae", "alpha",   "" }, {"Cae", "beta",    "" }},
			{{"Cae", "alpha",   "" }, {"Cae", "delta",   "" }},
			{{"Cae", "beta",    "" }, {"Cae", "gamma",   "1"}},
		},
		{	// Camelopardalis
			{{"Cam", "alpha",   "" }, {"Cam", "beta",    "" }},
			{{"Cam", "alpha",   "" }, {"Cam", "gamma",   "" }},
			{{"Cam", "beta",    "" }, {"Cam", "8",       "" }},
			{{"Cam", "alpha",   "" }, {"Cam", "51",      "" }},
		},
		{	// Cancer
			{{"Cnc", "alpha",   "" }, {"Cnc", "delta",   "" }},
			{{"Cnc", "delta",   "" }, {"Cnc", "beta",    "" }},
			{{"Cnc", "delta",   "" }, {"Cnc", "gamma",   "" }},
			{{"Cnc", "gamma",   "" }, {"Cnc", "iota",    "" }},
		},
		{	// Canes Venatici
			{{"CVn", "alpha",   "1"}, {"CVn", "beta",    "" }},
		},
		{	// Canis Major
			{{"CMa", "alpha",   "" }, {"CMa", "beta",    "" }},
			{{"CMa", "beta",    "" }, {"CMa", "nu",      "2"}},
			{{"CMa", "nu",      "2"}, {"CMa", "omicron", "1"}},
			{{"CMa", "omicron", "1"}, {"CMa", "epsilon", "" }},
			{{"CMa", "epsilon", "" }, {"CMa", "sigma",   "" }},
			{{"CMa", "sigma",   "" }, {"CMa", "delta",   "" }},
			{{"CMa", "delta",   "" }, {"CMa", "eta",     "" }},
			{{"CMa", "delta",   "" }, {"CMa", "alpha",   "" }},
			{{"CMa", "alpha",   "" }, {"CMa", "iota",    "" }},
			{{"CMa", "iota",    "" }, {"CMa", "gamma",   "" }},
			{{"CMa", "gamma",   "" }, {"CMa", "theta",   "" }},
			{{"CMa", "theta",   "" }, {"CMa", "iota",    "" }},
		},
		{	// Canis Minor
			{{"CMi", "alpha",   "" }, {"CMi", "beta",    "" }},
		},
		{	// Capricornus
			{{"Cap", "alpha",   "1"}, {"Cap", "beta",    "" }},
			{{"Cap", "beta",    "" }, {"Cap", "omega",   "" }},
			{{"Cap", "omega",   "" }, {"Cap", "zeta",    "" }},
			{{"Cap", "zeta",    "" }, {"Cap", "delta",   "" }},
			{{"Cap", "delta",   "" }, {"Cap", "gamma",   "" }},
			{{"Cap", "gamma",   "" }, {"Cap", "theta",   "" }},
			{{"Cap", "theta",   "" }, {"Cap", "alpha",   "1"}},
		},
		{	// Carina
			{{"Car", "alpha",   "" }, {"Car", "beta",    "" }},
			{{"Car", "beta",    "" }, {"Car", "omega",   "" }},
			{{"Car", "omega",   "" }, {"Car", "theta",   "" }},
			{{"Car", "theta",   "" }, {"Car", "eta",     "" }},
			{{"Car", "theta",   "" }, {"Car", "iota",    "" }},
			{{"Car", "iota",    "" }, {"Car", "epsilon", "" }},
			{{"Car", "epsilon", "" }, {"Car", "chi",     "" }},
		},
		{	// Cassiopeia
			{{"Cas", "alpha",   "" }, {"Cas", "beta",    "" }},
			{{"Cas", "alpha",   "" }, {"Cas", "gamma",   "" }},
			{{"Cas", "gamma",   "" }, {"Cas", "delta",   "" }},
			{{"Cas", "delta",   "" }, {"Cas", "epsilon", "" }},
		},
		{	// Centaurus
			{{"Cen", "alpha",   "1"}, {"Cen", "epsilon", "" }},
			{{"Cen", "beta",    "" }, {"Cen", "epsilon", "" }},
			{{"Cen", "epsilon", "" }, {"Cen", "gamma",   "" }},
			{{"Cen", "gamma",   "" }, {"Cen", "zeta",    "" }},
			{{"Cen", "zeta",    "" }, {"Cen", "epsilon", "" }},
			{{"Cen", "gamma",   "" }, {"Cen", "sigma",   "" }},
			{{"Cen", "sigma",   "" }, {"Cen", "rho",     "" }},
			{{"Cen", "rho",     "" }, {"Cen", "lambda",  "" }},
			{{"Cen", "sigma",   "" }, {"Cen", "delta",   "" }},
			{{"Cen", "delta",   "" }, {"Cen", "pi",      "" }},
			{{"Cen", "zeta",    "" }, {"Cen", "phi",     "" }},
			{{"Cen", "phi",     "" }, {"Cen", "eta",     "" }},
			{{"Cen", "eta",     "" }, {"Cen", "kappa",   "" }},
			{{"Cen", "phi",     "" }, {"Cen", "nu",      "" }},
			{{"Cen", "zeta",    "" }, {"Cen", "nu",      "" }},
			{{"Cen", "nu",      "" }, {"Cen", "iota",    "" }},
			{{"Cen", "nu",      "" }, {"Cen", "theta",   "" }},
			{{"Cen", "theta",   "" }, {"Cen", "psi",     "" }},
			{{"Cen", "psi",     "" }, {"Cen", "phi",     "" }},
			{{"Cen", "phi",     "" }, {"Cen", "eta",     "" }},
			{{"Cen", "eta",     "" }, {"Cen", "kappa",   "" }},
		},
		{	// Cepheus
			{{"Cep", "alpha",   "" }, {"Cep", "eta",     "" }},
			{{"Cep", "eta",     "" }, {"Cep", "theta",   "" }},
			{{"Cep", "alpha",   "" }, {"Cep", "mu",      "" }},
			{{"Cep", "mu",      "" }, {"Cep", "epsilon", "" }},
			{{"Cep", "epsilon", "" }, {"Cep", "zeta",    "" }},
			{{"Cep", "zeta",    "" }, {"Cep", "delta",   "" }},
			{{"Cep", "delta",   "" }, {"Cep", "iota",    "" }},
			{{"Cep", "iota",    "" }, {"Cep", "gamma",   "" }},
			{{"Cep", "gamma",   "" }, {"Cep", "beta",    "" }},
			{{"Cep", "beta",    "" }, {"Cep", "alpha",   "" }},
			{{"Cep", "beta",    "" }, {"Cep", "iota",    "" }},
		},
		{	// Cetus
			{{"Cet", "alpha",   "" }, {"Cet", "lambda",  "" }},
			{{"Cet", "lambda",  "" }, {"Cet", "mu",      "" }},
			{{"Cet", "mu",      "" }, {"Cet", "xi",      "2"}},
			{{"Cet", "xi",      "2"}, {"Cet", "nu",      "" }},
			{{"Cet", "nu",      "" }, {"Cet", "gamma",   "" }},
			{{"Cet", "gamma",   "" }, {"Cet", "alpha",   "" }},
			{{"Cet", "gamma",   "" }, {"Cet", "delta",   "" }},
			{{"Cet", "delta",   "" }, {"Cet", "omicron", "" }},
			{{"Cet", "omicron", "" }, {"Cet", "zeta",    "" }},
			{{"Cet", "zeta",    "" }, {"Cet", "theta",   "" }},
			{{"Cet", "theta",   "" }, {"Cet", "eta",     "" }},
			{{"Cet", "eta",     "" }, {"Cet", "iota",    "" }},
			{{"Cet", "iota",    "" }, {"Cet", "beta",    "" }},
			{{"Cet", "beta",    "" }, {"Cet", "tau",     "" }},
			{{"Cet", "tau",     "" }, {"Cet", "zeta",    "" }},
		},
		{	// Chamaeleon
			{{"Cha", "alpha",   "" }, {"Cha", "gamma",   "" }},
			{{"Cha", "gamma",   "" }, {"Cha", "beta",    "" }},
			{{"Cha", "beta",    "" }, {"Cha", "delta",   "2"}},
			{{"Cha", "delta",   "2"}, {"Cha", "theta",   "" }},
			{{"Cha", "theta",   "" }, {"Cha", "alpha",   "" }},
		},
		{	// Circinus
			{{"Cir", "alpha",   "" }, {"Cir", "delta",   "" }},
			{{"Cir", "delta",   "" }, {"Cir", "gamma",   "" }},
			{{"Cir", "alpha",   "" }, {"Cir", "theta",   "" }},
			{{"Cir", "theta",   "" }, {"Cir", "beta",    "" }},
		},
		{	// Columba
			{{"Col", "alpha",   "" }, {"Col", "omicron", "" }},
			{{"Col", "omicron", "" }, {"Col", "epsilon", "" }},
			{{"Col", "epsilon", "" }, {"Col", "beta",    "" }},
			{{"Col", "beta",    "" }, {"Col", "eta",     "" }},
			{{"Col", "eta",     "" }, {"Col", "gamma",   "" }},
			{{"Col", "gamma",   "" }, {"Col", "kappa",   "" }},
			{{"Col", "kappa",   "" }, {"Col", "lambda",  "" }},
			{{"Col", "lambda",  "" }, {"Col", "sigma",   "" }},
			{{"Col", "sigma",   "" }, {"Col", "nu",      "2"}},
			{{"Col", "nu",      "2"}, {"Col", "mu",      "" }},
			{{"Col", "mu",      "" }, {"Col", "alpha",   "" }},
			{{"Col", "theta",   "" }, {"Col", "kappa",   "" }},
			{{"Col", "kappa",   "" }, {"Col", "delta",   "" }},
		},
		{	// Coma Berenices
			{{"Com", "alpha",   "" }, {"Com", "beta",    "" }},
			{{"Com", "beta",    "" }, {"Com", "gamma",   "" }},
		},
		{	// Corona Australis
			{{"CrA", "zeta",    "" }, {"CrA", "delta",   "" }},
			{{"CrA", "delta",   "" }, {"CrA", "beta",    "" }},
			{{"CrA", "beta",    "" }, {"CrA", "alpha",   "" }},
			{{"CrA", "alpha",   "" }, {"CrA", "gamma",   "" }},
			{{"CrA", "gamma",   "" }, {"CrA", "epsilon", "" }},
			{{"CrA", "epsilon", "" }, {"CrA", "lambda",  "" }},
		},
		{	// Corona Borealis
			{{"CrB", "theta",   "" }, {"CrB", "beta",    "" }},
			{{"CrB", "beta",    "" }, {"CrB", "alpha",   "" }},
			{{"CrB", "alpha",   "" }, {"CrB", "gamma",   "" }},
			{{"CrB", "gamma",   "" }, {"CrB", "delta",   "" }},
			{{"CrB", "delta",   "" }, {"CrB", "epsilon", "" }},
			{{"CrB", "epsilon", "" }, {"CrB", "iota",    "" }},
		},
		{	// Corvus
			{{"Crv", "alpha",   "" }, {"Crv", "epsilon", "" }},
			{{"Crv", "epsilon", "" }, {"Crv", "beta",    "" }},
			{{"Crv", "beta",    "" }, {"Crv", "delta",   "" }},
			{{"Crv", "delta",   "" }, {"Crv", "gamma",   "" }},
			{{"Crv", "gamma",   "" }, {"Crv", "epsilon", "" }},
		},
		{	// Crater
			{{"Crt", "alpha",   "" }, {"Crt", "beta",    "" }},
			{{"Crt", "beta",    "" }, {"Crt", "gamma",   "" }},
			{{"Crt", "gamma",   "" }, {"Crt", "delta",   "" }},
			{{"Crt", "delta",   "" }, {"Crt", "alpha",   "" }},
			{{"Crt", "gamma",   "" }, {"Crt", "zeta",    "" }},
			{{"Crt", "zeta",    "" }, {"Crt", "eta",     "" }},
			{{"Crt", "delta",   "" }, {"Crt", "epsilon", "" }},
			{{"Crt", "epsilon", "" }, {"Crt", "theta",   "" }},
		},
		{	// Crux
			{{"Cru", "alpha",   "1"}, {"Cru", "gamma",   "" }},
			{{"Cru", "beta",    "" }, {"Cru", "delta",   "" }},
		},
		{	// Cygnus
			{{"Cyg", "alpha",   "" }, {"Cyg", "iota",    "1"}},
			{{"Cyg", "iota",    "1"}, {"Cyg", "kappa",   "" }},
			{{"Cyg", "iota",    "1"}, {"Cyg", "delta",   "" }},
			{{"Cyg", "delta",   "" }, {"Cyg", "gamma",   "" }},
			{{"Cyg", "gamma",   "" }, {"Cyg", "alpha",   "" }},
			{{"Cyg", "gamma",   "" }, {"Cyg", "epsilon", "" }},
			{{"Cyg", "epsilon", "" }, {"Cyg", "zeta",    "" }},
			{{"Cyg", "zeta",    "" }, {"Cyg", "nu",      "" }},
			{{"Cyg", "nu",      "" }, {"Cyg", "alpha",   "" }},
			{{"Cyg", "gamma",   "" }, {"Cyg", "eta",     "" }},
			{{"Cyg", "eta",     "" }, {"Cyg", "beta",    "1"}},
		},
		{	// Delphinus
			{{"Del", "alpha",   "" }, {"Del", "beta",    "" }},
			{{"Del", "beta",    "" }, {"Del", "delta",   "" }},
			{{"Del", "delta",   "" }, {"Del", "gamma",   "1"}},
			{{"Del", "gamma",   "1"}, {"Del", "alpha",   "" }},
			{{"Del", "beta",    "" }, {"Del", "epsilon", "" }},
		},
		{	// Dorado
			{{"Dor", "gamma",   "" }, {"Dor", "alpha",   "" }},
			{{"Dor", "alpha",   "" }, {"Dor", "zeta",    "" }},
			{{"Dor", "alpha",   "" }, {"Dor", "beta",    "" }},
			{{"Dor", "zeta",    "" }, {"Dor", "beta",    "" }},
			{{"Dor", "beta",    "" }, {"Dor", "delta",   "" }},
			{{"Dor", "beta",    "" }, {"Dor", "eta",     "2"}},
			{{"Dor", "delta",   "" }, {"Dor", "eta",     "2"}},
		},
		{	// Draco
			{{"Dra", "beta" ,   "" }, {"Dra", "gamma",   "" }},
			{{"Dra", "gamma",   "" }, {"Dra", "xi",      "" }},
			{{"Dra", "xi",      "" }, {"Dra", "nu",      "1"}},
			{{"Dra", "nu",      "1"}, {"Dra", "beta",    "" }},
			{{"Dra", "xi" ,     "" }, {"Dra", "delta",   "" }},
			{{"Dra", "delta" ,  "" }, {"Dra", "epsilon", "" }},
			{{"Dra", "epsilon" ,"" }, {"Dra", "chi",     "" }},
			{{"Dra", "chi",     "" }, {"Dra", "psi",     "1"}},
			{{"Dra", "psi",    "1" }, {"Dra", "zeta",    "" }},
			{{"Dra", "zeta",    "" }, {"Dra", "eta",     "" }},
			{{"Dra", "eta",     "" }, {"Dra", "theta",   "" }},
			{{"Dra", "theta",   "" }, {"Dra", "iota",    "" }},
			{{"Dra", "iota",    "" }, {"Dra", "alpha",   "" }},
			{{"Dra", "alpha",   "" }, {"Dra", "kappa",   "" }},
		},
		{	// Equuleus
			{{"Equ", "alpha",   "" }, {"Equ", "beta",    "" }},
			{{"Equ", "beta",    "" }, {"Equ", "delta",   "" }},
			{{"Equ", "delta",   "" }, {"Equ", "gamma",   "" }},
			{{"Equ", "gamma",   "" }, {"Equ", "alpha",   "" }},
		},
		{	// Eridanus
			{{"Eri", "alpha",   "" }, {"Eri", "chi",     "" }},
			{{"Eri", "chi",     "" }, {"Eri", "kappa",   "" }},
			{{"Eri", "kappa",   "" }, {"Eri", "iota",    "" }},
			{{"Eri", "iota",    "" }, {"Eri", "theta",   "1"}},
			{{"Eri", "theta",   "1"}, {"Eri", "upsilon", "2"}},
			{{"Eri", "upsilon", "2"}, {"Eri", "upsilon", "1"}},
			{{"Eri", "upsilon", "1"}, {"Eri", "tau",     "9"}},
			{{"Eri", "tau",     "9"}, {"Eri", "tau",     "8"}},
			{{"Eri", "tau",     "8"}, {"Eri", "tau",     "6"}},
			{{"Eri", "tau",     "6"}, {"Eri", "tau",     "5"}},
			{{"Eri", "tau",     "5"}, {"Eri", "tau",     "4"}},
			{{"Eri", "tau",     "4"}, {"Eri", "tau",     "3"}},
			{{"Eri", "tau",     "3"}, {"Eri", "tau",     "1"}},
			{{"Eri", "tau",     "1"}, {"Eri", "eta",     "" }},
			{{"Eri", "eta",     "" }, {"Eri", "epsilon", "" }},
			{{"Eri", "epsilon", "" }, {"Eri", "delta",   "" }},
			{{"Eri", "delta",   "" }, {"Eri", "pi",      "" }},
			{{"Eri", "pi",      "" }, {"Eri", "gamma",   "" }},
			{{"Eri", "gamma",   "" }, {"Eri", "omicron", "1"}},
			{{"Eri", "omicron", "1"}, {"Eri", "nu",      "" }},
			{{"Eri", "nu",      "" }, {"Eri", "mu",      "" }},
			{{"Eri", "mu",      "" }, {"Eri", "omega",   "" }},
			{{"Eri", "omega",   "" }, {"Eri", "beta",    "" }},
		},
		{	// Fornax
			{{"For", "alpha",   "" }, {"For", "beta",    "" }},
			{{"For", "beta",    "" }, {"For", "nu",      "" }},
			{{"For", "nu",      "" }, {"For", "omega",   "" }},
			{{"For", "omega",   "" }, {"For", "alpha",   "" }},
		},
		{	// Gemini
			{{"Gem", "alpha",   "" }, {"Gem", "tau",     "" }},
			{{"Gem", "tau",     "" }, {"Gem", "theta",   "" }},
			{{"Gem", "tau",     "" }, {"Gem", "epsilon", "" }},
			{{"Gem", "epsilon", "" }, {"Gem", "mu",      "" }},
			{{"Gem", "mu",      "" }, {"Gem", "eta",     "" }},
			{{"Gem", "epsilon", "" }, {"Gem", "nu",      "" }},
			{{"Gem", "tau",     "" }, {"Gem", "iota",    "" }},
			{{"Gem", "iota",    "" }, {"Gem", "upsilon", "" }},
			{{"Gem", "beta",    "" }, {"Gem", "upsilon", "" }},
			{{"Gem", "upsilon", "" }, {"Gem", "kappa",   "" }},
			{{"Gem", "upsilon", "" }, {"Gem", "delta",   "" }},
			{{"Gem", "delta",   "" }, {"Gem", "zeta",    "" }},
			{{"Gem", "zeta",    "" }, {"Gem", "gamma",   "" }},
			{{"Gem", "zeta",    "" }, {"Gem", "xi",      "" }},
		},
		{	// Grus
			{{"Gru", "gamma",   "" }, {"Gru", "lambda",  "" }},
			{{"Gru", "lambda",  "" }, {"Gru", "mu",      "1"}},
			{{"Gru", "mu",      "1"}, {"Gru", "alpha",   "" }},
			{{"Gru", "alpha",   "" }, {"Gru", "beta",    "" }},
			{{"Gru", "beta",    "" }, {"Gru", "iota",    "" }},
			{{"Gru", "iota",    "" }, {"Gru", "theta",   "" }},
			{{"Gru", "theta",   "" }, {"Gru", "delta",   "1"}},
			{{"Gru", "delta",   "1"}, {"Gru", "alpha",   "" }},
			{{"Gru", "beta",    "" }, {"Gru", "epsilon", "" }},
			{{"Gru", "epsilon", "" }, {"Gru", "zeta",    "" }},
		},
		{	// Hercules
			{{"Her", "alpha",   "1"}, {"Her", "beta",    "" }},
			{{"Her", "beta",    "" }, {"Her", "zeta",    "" }},
			{{"Her", "zeta",    "" }, {"Her", "epsilon", "" }},
			{{"Her", "epsilon", "" }, {"Her", "delta",   "" }},
			{{"Her", "delta",   "" }, {"Her", "alpha",   "1"}},
			{{"Her", "beta",    "" }, {"Her", "gamma",   "" }},
			{{"Her", "gamma",   "" }, {"Her", "omega",   "" }},
			{{"Her", "zeta",    "" }, {"Her", "eta",     "" }},
			{{"Her", "eta",     "" }, {"Her", "pi",      "" }},
			{{"Her", "pi",      "" }, {"Her", "epsilon", "" }},
			{{"Her", "delta",   "" }, {"Her", "lambda",  "" }},
			{{"Her", "lambda",  "" }, {"Her", "mu",      "" }},
			{{"Her", "mu",      "" }, {"Her", "xi",      "" }},
			{{"Her", "xi",      "" }, {"Her", "omicron", "" }},
			{{"Her", "pi",      "" }, {"Her", "rho",     "" }},
			{{"Her", "rho",     "" }, {"Her", "theta",   "" }},
			{{"Her", "theta",   "" }, {"Her", "iota",    "" }},
			{{"Her", "eta",     "" }, {"Her", "sigma",   "" }},
			{{"Her", "sigma",   "" }, {"Her", "tau",     "" }},
			{{"Her", "tau",     "" }, {"Her", "phi",     "" }},
			{{"Her", "phi",     "" }, {"Her", "chi",     "" }},
		},
		{	// Horologium
			{{"Hor", "beta",    "" }, {"Hor", "mu",      "" }},
			{{"Hor", "mu",      "" }, {"Hor", "zeta",    "" }},
			{{"Hor", "zeta",    "" }, {"Hor", "eta",     "" }},
			{{"Hor", "eta",     "" }, {"Hor", "iota",    "" }},
			{{"Hor", "iota",    "" }, {"Hor", "alpha",   "" }},
		},
		{	// Hydra
			{{"Hya", "pi",      "" }, {"Hya", "gamma",   "" }},
			{{"Hya", "gamma",   "" }, {"Hya", "beta",    "" }},
			{{"Hya", "beta",    "" }, {"Hya", "xi",      "" }},
			{{"Hya", "xi",      "" }, {"Crt", "beta",    "" }},
			{{"Crt", "beta",    "" }, {"Crt", "alpha",   "" }},
			{{"Crt", "alpha",   "" }, {"Hya", "nu",      "" }},
			{{"Hya", "nu",      "" }, {"Hya", "mu",      "" }},
			{{"Hya", "mu",      "" }, {"Hya", "lambda",  "" }},
			{{"Hya", "lambda",  "" }, {"Hya", "upsilon", "1"}},
			{{"Hya", "upsilon", "1"}, {"Hya", "alpha",   "" }},
			{{"Hya", "alpha",   "" }, {"Hya", "iota",    "" }},
			{{"Hya", "iota",    "" }, {"Hya", "theta",   "" }},
			{{"Hya", "theta",   "" }, {"Hya", "zeta",    "" }},
			{{"Hya", "zeta",    "" }, {"Hya", "epsilon", "" }},
			{{"Hya", "epsilon", "" }, {"Hya", "delta",   "" }},
			{{"Hya", "delta",   "" }, {"Hya", "sigma",   "" }},
			{{"Hya", "sigma",   "" }, {"Hya", "eta",     "" }},
			{{"Hya", "eta",     "" }, {"Hya", "rho",     "" }},
		},
		{	// Hydrus
			{{"Hyi", "alpha",   "" }, {"Hyi", "eta",     "2"}},
			{{"Hyi", "eta",     "2"}, {"Hyi", "delta",   "" }},
			{{"Hyi", "delta",   "" }, {"Hyi", "epsilon", "" }},
			{{"Hyi", "epsilon", "" }, {"Hyi", "beta",    "" }},
			{{"Hyi", "beta",    "" }, {"Hyi", "gamma",   "" }},
		},
		{	// Indus
			{{"Ind", "alpha",   "" }, {"Ind", "beta",    "" }},
			{{"Ind", "beta",    "" }, {"Ind", "delta",   "" }},
			{{"Ind", "delta",   "" }, {"Ind", "theta",   "" }},
			{{"Ind", "theta",   "" }, {"Ind", "alpha",   "" }},
		},
		{	// Lacerta
			{{"Lac", "alpha",   "" }, {"Lac", "beta",    "" }},
			{{"Lac", "beta",    "" }, {"Lac", "4",       "" }},
			{{"Lac", "4",       "" }, {"Lac", "5",       "" }},
			{{"Lac", "5",       "" }, {"Lac", "alpha",   "" }},
			{{"Lac", "5",       "" }, {"Lac", "2",       "" }},
			{{"Lac", "2",       "" }, {"Lac", "6",       "" }},
			{{"Lac", "6",       "" }, {"Lac", "11",      "" }},
			{{"Lac", "11",      "" }, {"Lac", "5",       "" }},
			{{"Lac", "6",       "" }, {"Lac", "1",       "" }},
		},
		{	// Leo
			{{"Leo", "alpha",   "" }, {"Leo", "eta",     "" }},
			{{"Leo", "eta",     "" }, {"Leo", "gamma",   "1"}},
			{{"Leo", "gamma",   "1"}, {"Leo", "zeta",    "" }},
			{{"Leo", "zeta",    "" }, {"Leo", "mu",      "" }},
			{{"Leo", "mu",      "" }, {"Leo", "epsilon", "" }},
			{{"Leo", "epsilon", "" }, {"Leo", "eta",     "" }},
			{{"Leo", "mu",      "" }, {"Leo", "kappa",   "" }},
			{{"Leo", "kappa",   "" }, {"Leo", "lambda",  "" }},
			{{"Leo", "lambda",  "" }, {"Leo", "epsilon", "" }},
			{{"Leo", "sigma",   "" }, {"Leo", "iota",    "" }},
			{{"Leo", "iota",    "" }, {"Leo", "theta",   "" }},
			{{"Leo", "theta",   "" }, {"Leo", "beta",    "" }},
			{{"Leo", "beta",    "" }, {"Leo", "delta",   "" }},
			{{"Leo", "delta",   "" }, {"Leo", "theta",   "" }},
			{{"Leo", "delta",   "" }, {"Leo", "gamma",   "1"}},
			{{"Leo", "theta",   "" }, {"Leo", "eta",     "" }},
		},
		{	// Leo Minor
			{{"LMi", "21",      "" }, {"LMi", "beta",    "" }},
			{{"LMi", "46",      "" }, {"LMi", "beta",    "" }},
			{{"LMi", "46",      "" }, {"LMi", "30",      "" }},
			{{"LMi", "21",      "" }, {"LMi", "30",      "" }},
			{{"LMi", "21",      "" }, {"LMi", "11",      "" }},
		},
		{	// Lepus
			{{"Lep", "alpha",   "" }, {"Lep", "beta",    "" }},
			{{"Lep", "beta",    "" }, {"Lep", "gamma",   "" }},
			{{"Lep", "gamma",   "" }, {"Lep", "delta",   "" }},
			{{"Lep", "delta",   "" }, {"Lep", "theta",   "" }},
			{{"Lep", "theta",   "" }, {"Lep", "eta",     "" }},
			{{"Lep", "eta",     "" }, {"Lep", "zeta",    "" }},
			{{"Lep", "zeta",    "" }, {"Lep", "alpha",   "" }},
			{{"Lep", "alpha",   "" }, {"Lep", "mu",      "" }},
			{{"Lep", "mu",      "" }, {"Lep", "lambda",  "" }},
			{{"Lep", "mu",      "" }, {"Lep", "kappa",   "" }},
			{{"Lep", "mu",      "" }, {"Lep", "epsilon", "" }},
			{{"Lep", "epsilon", "" }, {"Lep", "beta",    "" }},
		},
		{	// Libra
			{{"Lib", "alpha",   "1"}, {"Lib", "beta",    "" }},
			{{"Lib", "beta",    "" }, {"Lib", "gamma",   "" }},
			{{"Lib", "gamma",   "" }, {"Lib", "alpha",   "1"}},
			{{"Lib", "alpha",   "1"}, {"Lib", "sigma",   "" }},
			{{"Lib", "gamma",   "" }, {"Lib", "upsilon", "" }},
			{{"Lib", "upsilon", "" }, {"Lib", "tau",     "" }},
		},
		{	// Lupus
			{{"Lup", "alpha",   "" }, {"Lup", "zeta",    "" }},
			{{"Lup", "zeta",    "" }, {"Lup", "eta",     "" }},
			{{"Lup", "eta",     "" }, {"Lup", "chi",     "" }},
			{{"Lup", "chi",     "" }, {"Lup", "phi",     "1"}},
			{{"Lup", "phi",     "1"}, {"Lup", "eta",     "" }},
			{{"Lup", "eta",     "" }, {"Lup", "gamma",   "" }},
			{{"Lup", "gamma",   "" }, {"Lup", "epsilon", "" }},
			{{"Lup", "epsilon", "" }, {"Lup", "mu",      "" }},
			{{"Lup", "mu",      "" }, {"Lup", "zeta",    "" }},
			{{"Lup", "gamma",   "" }, {"Lup", "delta",   "" }},
			{{"Lup", "delta",   "" }, {"Lup", "beta",    "" }},
		},
		{	// Lynx
			{{"Lyn", "alpha",   "" }, {"Lyn", "38",      "" }},
			{{"Lyn", "38",      "" }, {"Lyn", "31",      "" }},
			{{"Lyn", "31",      "" }, {"Lyn", "21",      "" }},
			{{"Lyn", "21",      "" }, {"Lyn", "15",      "" }},
			{{"Lyn", "15",      "" }, {"Lyn", "2",       "" }},
		},
		{	// Lyra
			{{"Lyr", "alpha",   "" }, {"Lyr", "zeta",    "1"}},
			{{"Lyr", "zeta",    "1"}, {"Lyr", "beta",    "" }},
			{{"Lyr", "beta",    "" }, {"Lyr", "gamma",   "" }},
			{{"Lyr", "gamma",   "" }, {"Lyr", "delta",   "1"}},
			{{"Lyr", "delta",   "1"}, {"Lyr", "zeta",    "1"}},
			{{"Lyr", "zeta",    "1"}, {"Lyr", "epsilon", "1"}},
			{{"Lyr", "epsilon", "1"}, {"Lyr", "alpha",   "" }},
		},
		{	// Mensa
			{{"Men", "mu",      "" }, {"Men", "beta",    "" }},
			{{"Men", "beta",    "" }, {"Men", "lambda",  "" }},
			{{"Men", "lambda",  "" }, {"Men", "alpha",   "" }},
			{{"Men", "alpha",   "" }, {"Men", "gamma",   "" }},
			{{"Men", "gamma",   "" }, {"Men", "eta",     "" }},
			{{"Men", "eta",     "" }, {"Men", "beta",    "" }},
		},
		{	// Microscopium
			{{"Mic", "alpha",   "" }, {"Mic", "gamma",   "" }},
			{{"Mic", "gamma",   "" }, {"Mic", "epsilon", "" }},
			{{"Mic", "epsilon", "" }, {"Mic", "theta",   "1"}},
		},
		{	// Monoceros
			{{"Mon", "alpha",   "" }, {"Mon", "zeta",    "" }},
			{{"Mon", "zeta",    "" }, {"Mon", "delta",   "" }},
			{{"Mon", "delta",   "" }, {"Mon", "beta",    "" }},
			{{"Mon", "beta",    "" }, {"Mon", "gamma",   "" }},
			{{"Mon", "delta",   "" }, {"Mon", "18",      "" }},
			{{"Mon", "18",      "" }, {"Mon", "epsilon", "" }},
			{{"Mon", "epsilon", "" }, {"Mon", "13",      "" }},
			{{"Mon", "13",      "" }, {"Mon", "18",      "" }},
			{{"Mon", "13",      "" }, {"Mon", "15",      "" }},
		},
		{	// Musca
			{{"Mus", "alpha",   "" }, {"Mus", "beta",    "" }},
			{{"Mus", "beta",    "" }, {"Mus", "delta",   "" }},
			{{"Mus", "delta",   "" }, {"Mus", "gamma",   "" }},
			{{"Mus", "gamma",   "" }, {"Mus", "alpha",   "" }},
			{{"Mus", "alpha",   "" }, {"Mus", "epsilon", "" }},
			{{"Mus", "epsilon", "" }, {"Mus", "lambda",  "" }},
		},
		{	// Norma
			{{"Nor", "delta",   "" }, {"Nor", "epsilon", "" }},
			{{"Nor", "epsilon", "" }, {"Nor", "gamma",   "2"}},
			{{"Nor", "gamma",   "2"}, {"Nor", "eta",     "" }},
			{{"Nor", "eta",     "" }, {"Nor", "delta",   "" }},
		},
		{	// Octans
			{{"Oct", "beta",    "" }, {"Oct", "delta",   "" }},
			{{"Oct", "delta",   "" }, {"Oct", "nu",      "" }},
			{{"Oct", "nu",      "" }, {"Oct", "beta",    "" }},
		},
		{	// Ophiuchus
			{{"Oph", "alpha",   "" }, {"Oph", "beta",    "" }},
			{{"Oph", "beta",    "" }, {"Oph", "gamma",   "" }},
			{{"Oph", "gamma",   "" }, {"Oph", "nu",      "" }},
			{{"Oph", "nu",      "" }, {"Ser", "xi",      "" }},
			{{"Ser", "xi",      "" }, {"Oph", "eta",     "" }},
			{{"Oph", "eta",     "" }, {"Oph", "theta",   "" }},
			{{"Oph", "eta",     "" }, {"Oph", "zeta",    "" }},
			{{"Oph", "zeta",    "" }, {"Oph", "phi",     "" }},
			{{"Oph", "phi",     "" }, {"Oph", "psi",     "" }},
			{{"Oph", "zeta",    "" }, {"Oph", "kappa",   "" }},
			{{"Oph", "kappa",   "" }, {"Oph", "alpha",   "" }},
			{{"Oph", "zeta",    "" }, {"Oph", "upsilon", "" }},
			{{"Oph", "upsilon", "" }, {"Oph", "epsilon", "" }},
			{{"Oph", "epsilon", "" }, {"Oph", "delta",   "" }},
			{{"Oph", "delta",   "" }, {"Oph", "lambda",  "" }},
			{{"Oph", "lambda",  "" }, {"Oph", "kappa",   "" }},
		},
		{	// Orion
			{{"Ori", "beta",    "" }, {"Ori", "eta",     "" }},
			{{"Ori", "eta",     "" }, {"Ori", "delta",   "" }},
			{{"Ori", "delta",   "" }, {"Ori", "gamma",   "" }},
			{{"Ori", "gamma",   "" }, {"Ori", "lambda",  "" }},
			{{"Ori", "lambda",  "" }, {"Ori", "alpha",   "" }},
			{{"Ori", "alpha",   "" }, {"Ori", "zeta",    "" }},
			{{"Ori", "zeta",    "" }, {"Ori", "kappa",   "" }},
			{{"Ori", "zeta",    "" }, {"Ori", "epsilon", "" }},
			{{"Ori", "epsilon", "" }, {"Ori", "delta",   "" }},
			{{"Ori", "alpha",   "" }, {"Ori", "gamma",   "" }},
			{{"Ori", "alpha",   "" }, {"Ori", "mu",      "" }},
			{{"Ori", "mu",      "" }, {"Ori", "xi",      "" }},
			{{"Ori", "xi",      "" }, {"Ori", "chi",     "2"}},
			{{"Ori", "chi",     "2"}, {"Ori", "chi",     "1"}},
			{{"Ori", "chi",     "1"}, {"Ori", "xi",      "" }},
			{{"Ori", "gamma",   "" }, {"Ori", "pi",      "3"}},
			{{"Ori", "pi",      "3"}, {"Ori", "pi",      "4"}},
			{{"Ori", "pi",      "4"}, {"Ori", "pi",      "5"}},
			{{"Ori", "pi",      "5"}, {"Ori", "pi",      "6"}},
			{{"Ori", "pi",      "3"}, {"Ori", "pi",      "2"}},
			{{"Ori", "pi",      "2"}, {"Ori", "omicron", "2"}},
		},
		{	// Pavo
			{{"Pav", "alpha",   "" }, {"Pav", "gamma",   "" }},
			{{"Pav", "gamma",   "" }, {"Pav", "beta",    "" }},
			{{"Pav", "beta",    "" }, {"Pav", "delta",   "" }},
			{{"Pav", "delta",   "" }, {"Pav", "alpha",   "" }},
			{{"Pav", "delta",   "" }, {"Pav", "epsilon", "" }},
			{{"Pav", "delta",   "" }, {"Pav", "zeta",    "" }},
			{{"Pav", "delta",   "" }, {"Pav", "kappa",   "" }},
			{{"Pav", "kappa",   "" }, {"Pav", "pi",      "" }},
			{{"Pav", "pi",      "" }, {"Pav", "xi",      "" }},
			{{"Pav", "xi",      "" }, {"Pav", "lambda",  "" }},
			{{"Pav", "lambda",  "" }, {"Pav", "delta",   "" }},
			{{"Pav", "pi",      "" }, {"Pav", "eta",     "" }},
		},
		{	// Pegasus
			{{"Peg", "alpha",   "" }, {"Peg", "gamma",   "" }},
			{{"Peg", "gamma",   "" }, {"And", "alpha",   "" }},
			{{"And", "alpha",   "" }, {"Peg", "beta",    "" }},
			{{"Peg", "beta",    "" }, {"Peg", "alpha",   "" }},
			{{"Peg", "alpha",   "" }, {"Peg", "zeta",    "" }},
			{{"Peg", "zeta",    "" }, {"Peg", "theta",   "" }},
			{{"Peg", "theta",   "" }, {"Peg", "epsilon", "" }},
			{{"Peg", "beta",    "" }, {"Peg", "lambda",  "" }},
			{{"Peg", "lambda",  "" }, {"Peg", "iota",    "" }},
			{{"Peg", "iota",    "" }, {"Peg", "kappa",   "" }},
			{{"Peg", "beta",    "" }, {"Peg", "eta",     "" }},
			{{"Peg", "eta",     "" }, {"Peg", "pi",      "1"}},
		},
		{	// Perseus
			{{"Per", "alpha",   "" }, {"Per", "gamma",   "" }},
			{{"Per", "gamma",   "" }, {"Per", "eta",     "" }},
			{{"Per", "eta",     "" }, {"Per", "tau",     "" }},
			{{"Per", "tau",     "" }, {"Per", "iota",    "" }},
			{{"Per", "iota",    "" }, {"Per", "alpha",   "" }},
			{{"Per", "gamma",   "" }, {"Per", "tau",     "" }},
			{{"Per", "iota",    "" }, {"Per", "theta",   "" }},
			{{"Per", "theta",   "" }, {"Per", "phi",     "" }},
			{{"Per", "alpha",   "" }, {"Per", "delta",   "" }},
			{{"Per", "delta",   "" }, {"Per", "mu",      "" }},
			{{"Per", "mu",      "" }, {"Per", "lambda",  "" }},
			{{"Per", "delta",   "" }, {"Per", "epsilon", "" }},
			{{"Per", "epsilon", "" }, {"Per", "xi",      "" }},
			{{"Per", "xi",      "" }, {"Per", "zeta",    "" }},
			{{"Per", "zeta",    "" }, {"Per", "omicron", "" }},
			{{"Per", "epsilon", "" }, {"Per", "beta",    "" }},
			{{"Per", "beta",    "" }, {"Per", "rho",     "" }},
			{{"Per", "beta",    "" }, {"Per", "kappa",   "" }},
			{{"Per", "kappa",   "" }, {"Per", "iota",    "" }},
		},
		{	// Phoenix
			{{"Phe", "alpha",   "" }, {"Phe", "beta",    "" }},
			{{"Phe", "beta",    "" }, {"Phe", "zeta",    "" }},
			{{"Phe", "zeta",    "" }, {"Phe", "eta",     "" }},
			{{"Phe", "eta",     "" }, {"Phe", "epsilon", "" }},
			{{"Phe", "epsilon", "" }, {"Phe", "alpha",   "" }},
			{{"Phe", "beta",    "" }, {"Phe", "nu",      "" }},
			{{"Phe", "nu",      "" }, {"Phe", "gamma",   "" }},
			{{"Phe", "gamma",   "" }, {"Phe", "delta",   "" }},
			{{"Phe", "epsilon", "" }, {"Phe", "iota",    "" }},
			{{"Phe", "iota",    "" }, {"Phe", "sigma",   "" }},
			{{"Phe", "sigma",   "" }, {"Phe", "pi",      "" }},
		},
		{	// Pictor
			{{"Pic", "alpha",   "" }, {"Pic", "beta",    "" }},
			{{"Pic", "alpha",   "" }, {"Pic", "gamma",   "" }},
			{{"Pic", "alpha",   "" }, {"Pic", "iota",    "" }},
		},
		{	// Pisces
			{{"Psc", "phi",     "" }, {"Psc", "upsilon", "" }},
			{{"Psc", "upsilon", "" }, {"Psc", "tau",     "" }},
			{{"Psc", "tau",     "" }, {"Psc", "phi",     "" }},
			{{"Psc", "phi",     "" }, {"Psc", "eta",     "" }},
			{{"Psc", "eta",     "" }, {"Psc", "omicron", "" }},
			{{"Psc", "omicron", "" }, {"Psc", "alpha",   "" }},
			{{"Psc", "alpha",   "" }, {"Psc", "nu",      "" }},
			{{"Psc", "nu",      "" }, {"Psc", "epsilon", "" }},
			{{"Psc", "epsilon", "" }, {"Psc", "omega",   "" }},
			{{"Psc", "omega",   "" }, {"Psc", "iota",    "" }},
			{{"Psc", "iota",    "" }, {"Psc", "theta",   "" }},
			{{"Psc", "theta",   "" }, {"Psc", "gamma",   "" }},
			{{"Psc", "gamma",   "" }, {"Psc", "kappa",   "" }},
			{{"Psc", "kappa",   "" }, {"Psc", "lambda",  "" }},
			{{"Psc", "lambda",  "" }, {"Psc", "iota",    "" }},
		},
		{	// Piscis Austrinus
			{{"PsA", "alpha",   "" }, {"PsA", "epsilon", "" }},
			{{"PsA", "epsilon", "" }, {"PsA", "mu",      "" }},
			{{"PsA", "mu",      "" }, {"PsA", "theta",   "" }},
			{{"PsA", "theta",   "" }, {"PsA", "iota",    "" }},
			{{"PsA", "iota",    "" }, {"PsA", "mu",      "" }},
			{{"PsA", "mu",      "" }, {"PsA", "beta",    "" }},
			{{"PsA", "beta",    "" }, {"PsA", "gamma",   "" }},
			{{"PsA", "gamma",   "" }, {"PsA", "delta",   "" }},
			{{"PsA", "delta",   "" }, {"PsA", "alpha",   "" }},
		},
		{	// Puppis
			{{"Vel", "gamma",   "1"}, {"Pup", "zeta",    "" }},
			{{"Pup", "zeta",    "" }, {"Pup", "xi",      "" }},
			{{"Pup", "xi",      "" }, {"Pup", "pi",      "" }},
			{{"Pup", "pi",      "" }, {"Pup", "nu",      "" }},
			{{"Pup", "nu",      "" }, {"Car", "alpha",   "" }},
		},
		{	// Pyxis
			{{"Pyx", "gamma",   "" }, {"Pyx", "alpha",   "" }},
			{{"Pyx", "alpha",   "" }, {"Pyx", "beta",    "" }},
			{{"Pyx", "alpha",   "" }, {"Vel", "gamma",   "1"}},
		},
		{	// Reticulum
			{{"Ret", "alpha",   "" }, {"Ret", "beta",    "" }},
			{{"Ret", "beta",    "" }, {"Ret", "delta",   "" }},
			{{"Ret", "delta",   "" }, {"Ret", "epsilon", "" }},
			{{"Ret", "epsilon", "" }, {"Ret", "alpha",   "" }},
		},
		{	// Sagitta
			{{"Sge", "alpha",   "" }, {"Sge", "delta",   "" }},
			{{"Sge", "beta",    "" }, {"Sge", "delta",   "" }},
			{{"Sge", "delta",   "" }, {"Sge", "gamma",   "" }},
			{{"Sge", "gamma",   "" }, {"Sge", "eta",     "" }},
		},
		{	// Sagittarius
			{{"Sgr", "alpha",   "" }, {"Sgr", "iota",    "" }},
			{{"Sgr", "beta",    "1"}, {"Sgr", "iota",    "" }},
			{{"Sgr", "iota",    "" }, {"Sgr", "theta",   "1"}},
			{{"Sgr", "theta",   "1"}, {"Sgr", "62",      "" }},
			{{"Sgr", "62",      "" }, {"Sgr", "52",      "" }},
			{{"Sgr", "52",      "" }, {"Sgr", "tau",     "" }},
			{{"Sgr", "tau",     "" }, {"Sgr", "sigma",   "" }},
			{{"Sgr", "sigma",   "" }, {"Sgr", "phi",     "" }},
			{{"Sgr", "phi",     "" }, {"Sgr", "zeta",    "" }},
			{{"Sgr", "zeta",    "" }, {"Sgr", "tau",     "" }},
			{{"Sgr", "sigma",   "" }, {"Sgr", "omicron", "" }},
			{{"Sgr", "omicron", "" }, {"Sgr", "pi",      "" }},
			{{"Sgr", "pi",      "" }, {"Sgr", "rho",     "1"}},
			{{"Sgr", "phi",     "" }, {"Sgr", "lambda",  "" }},
			{{"Sgr", "lambda",  "" }, {"Sgr", "mu",      "" }},
			{{"Sgr", "lambda",  "" }, {"Sgr", "delta",   "" }},
			{{"Sgr", "delta",   "" }, {"Sgr", "epsilon", "" }},
			{{"Sgr", "epsilon", "" }, {"Sgr", "eta",     "" }},
			{{"Sgr", "delta",   "" }, {"Sgr", "gamma",   "1"}},
			{{"Sgr", "gamma",   "1"}, {"Sgr", "3",       "" }},
			{{"Sgr", "gamma",   "1"}, {"Sgr", "epsilon", "" }},
		},
		{	// Scorpius
			{{"Sco", "beta",    "1"}, {"Sco", "delta",   "" }},
			{{"Sco", "delta",   "" }, {"Sco", "pi",      "" }},
			{{"Sco", "delta",   "" }, {"Sco", "sigma",   "" }},
			{{"Sco", "sigma",   "" }, {"Sco", "alpha",   "" }},
			{{"Sco", "alpha",   "" }, {"Sco", "tau",     "" }},
			{{"Sco", "tau",     "" }, {"Sco", "epsilon", "" }},
			{{"Sco", "epsilon", "" }, {"Sco", "mu",      "1"}},
			{{"Sco", "mu",      "1"}, {"Sco", "zeta",    "1"}},
			{{"Sco", "zeta",    "1"}, {"Sco", "eta",     "" }},
			{{"Sco", "eta",     "" }, {"Sco", "theta",   "" }},
			{{"Sco", "theta",   "" }, {"Sco", "iota",    "1"}},
			{{"Sco", "iota",    "1"}, {"Sco", "kappa",   "" }},
			{{"Sco", "kappa",   "" }, {"Sco", "upsilon", "" }},
			{{"Sco", "upsilon", "" }, {"Sco", "lambda",  "" }},
		},
		{	// Sculptor
			{{"Scl", "alpha",   "" }, {"Scl", "iota",    "" }},
			{{"Scl", "iota",    "" }, {"Scl", "delta",   "" }},
			{{"Scl", "delta",   "" }, {"Scl", "gamma",   "" }},
			{{"Scl", "gamma",   "" }, {"Scl", "beta",    "" }},
		},
		{	// Scutum
			{{"Sct", "alpha",   "" }, {"Sct", "beta",    "" }},
			{{"Sct", "beta",    "" }, {"Sct", "delta",   "" }},
			{{"Sct", "delta",   "" }, {"Sct", "gamma",   "" }},
			{{"Sct", "gamma",   "" }, {"Sct", "alpha",   "" }},
		},
		{	// Serpens
			{{"Oph", "delta",   "" }, {"Ser", "mu",      "" }},
			{{"Ser", "mu",      "" }, {"Ser", "omega",   "" }},
			{{"Ser", "omega",   "" }, {"Ser", "epsilon", "" }},
			{{"Ser", "epsilon", "" }, {"Ser", "alpha",   "" }},
			{{"Ser", "alpha",   "" }, {"Ser", "delta",   "" }},
			{{"Ser", "delta",   "" }, {"Ser", "beta",    "" }},
			{{"Ser", "beta",    "" }, {"Ser", "gamma",   "" }},
			{{"Ser", "gamma",   "" }, {"Ser", "kappa",   "" }},
			{{"Ser", "kappa",   "" }, {"Ser", "iota",    "" }},
			{{"Ser", "iota",    "" }, {"Ser", "beta",    "" }},
			{{"Oph", "eta",     "" }, {"Ser", "xi",      "" }},
			{{"Ser", "xi",      "" }, {"Oph", "nu",      "" }},
			{{"Oph", "nu",      "" }, {"Ser", "eta",     "" }},
			{{"Ser", "eta",     "" }, {"Ser", "theta",   "1"}},
		},
		{	// Sextans
			{{"Sex", "alpha",   "" }, {"Sex", "beta",    "" }},
			{{"Sex", "beta",    "" }, {"Sex", "delta",   "" }},
			{{"Sex", "delta",   "" }, {"Sex", "gamma",   "" }},
			{{"Sex", "gamma",   "" }, {"Sex", "alpha",   "" }},
		},
		{	// Taurus
			{{"Tau", "alpha",   "" }, {"Tau", "zeta",    "" }},
			{{"Tau", "alpha",   "" }, {"Tau", "theta",   "1"}},
			{{"Tau", "theta",   "1"}, {"Tau", "gamma",   "" }},
			{{"Tau", "gamma",   "" }, {"Tau", "delta",   "1"}},
			{{"Tau", "delta",   "1"}, {"Tau", "epsilon", "" }},
			{{"Tau", "epsilon", "" }, {"Tau", "beta",    "" }},
			{{"Tau", "gamma",   "" }, {"Tau", "lambda",  "" }},
			{{"Tau", "lambda",  "" }, {"Tau", "mu",      "" }},
			{{"Tau", "mu",      "" }, {"Tau", "nu",      "" }},
			{{"Tau", "lambda",  "" }, {"Tau", "5",       "" }},
			{{"Tau", "5",       "" }, {"Tau", "xi",      "" }},
			{{"Tau", "xi",      "" }, {"Tau", "omicron", "" }},
		},
		{	// Telescopium
			{{"Tel", "epsilon", "" }, {"Tel", "alpha",   "" }},
			{{"Tel", "alpha",   "" }, {"Tel", "rho",     "" }},
			{{"Tel", "rho",     "" }, {"Tel", "eta",     "" }},
			{{"Tel", "eta",     "" }, {"Tel", "mu",      "" }},
			{{"Tel", "mu",      "" }, {"Tel", "nu",      "" }},
			{{"Tel", "nu",      "" }, {"Tel", "xi",      "" }},
			{{"Tel", "xi",      "" }, {"Tel", "iota",    "" }},
		},
		{	// Triangulum
			{{"Tri", "alpha",   "" }, {"Tri", "beta",     "" }},
			{{"Tri", "beta",    "" }, {"Tri", "gamma",    "" }},
			{{"Tri", "gamma",   "" }, {"Tri", "alpha",    "" }},
		},
		{	// Triangulum Australe
			{{"TrA", "alpha",   "" }, {"TrA", "beta",     "" }},
			{{"TrA", "beta",    "" }, {"TrA", "gamma",    "" }},
			{{"TrA", "gamma",   "" }, {"TrA", "alpha",    "" }},
		},
		{	// Tucana
			{{"Tuc", "alpha",   "" }, {"Tuc", "gamma",    "" }},
			{{"Tuc", "gamma",   "" }, {"Tuc", "beta",     "1"}},
			{{"Tuc", "beta",    "1"}, {"Tuc", "zeta",     "" }},
			{{"Tuc", "zeta",    "" }, {"Tuc", "epsilon",  "" }},
			{{"Tuc", "epsilon", "" }, {"Tuc", "delta",    "" }},
			{{"Tuc", "delta",   "" }, {"Tuc", "alpha",    "" }},
		},
		{	// Ursa Major
			{{"UMa", "alpha",   "" }, {"UMa", "beta",     "" }},
			{{"UMa", "beta",    "" }, {"UMa", "gamma",    "" }},
			{{"UMa", "gamma",   "" }, {"UMa", "delta",    "" }},
			{{"UMa", "delta",   "" }, {"UMa", "alpha",    "" }},
			{{"UMa", "delta",   "" }, {"UMa", "epsilon",  "" }},
			{{"UMa", "epsilon", "" }, {"UMa", "zeta",     "" }},
			{{"UMa", "zeta",    "" }, {"UMa", "eta",      "" }},
			{{"UMa", "alpha",   "" }, {"UMa", "tau",      "" }},
			{{"UMa", "tau",     "" }, {"UMa", "omicron",  "" }},
			{{"UMa", "omicron", "" }, {"UMa", "upsilon",  "" }},
			{{"UMa", "upsilon", "" }, {"UMa", "beta",     "" }},
			{{"UMa", "upsilon", "" }, {"UMa", "tau",      "" }},
			{{"UMa", "upsilon", "" }, {"UMa", "theta",    "" }},
			{{"UMa", "theta",   "" }, {"UMa", "kappa",    "" }},
			{{"UMa", "gamma",   "" }, {"UMa", "chi",      "" }},
			{{"UMa", "chi",     "" }, {"UMa", "nu",       "" }},
			{{"UMa", "nu",      "" }, {"UMa", "xi",       "" }},
			{{"UMa", "chi",     "" }, {"UMa", "psi",      "" }},
			{{"UMa", "psi",     "" }, {"UMa", "omega",    "" }},
			{{"UMa", "omega",   "" }, {"UMa", "mu",       "" }},
			{{"UMa", "mu",      "" }, {"UMa", "lambda",   "" }},
		},
		{	// Ursa Minor
			{{"UMi", "alpha",   "" }, {"UMi", "delta",    "" }},
			{{"UMi", "delta",   "" }, {"UMi", "epsilon",  "" }},
			{{"UMi", "epsilon", "" }, {"UMi", "zeta",     "" }},
			{{"UMi", "zeta",    "" }, {"UMi", "eta",      "" }},
			{{"UMi", "eta",     "" }, {"UMi", "gamma",    "" }},
			{{"UMi", "gamma",   "" }, {"UMi", "beta",     "" }},
			{{"UMi", "beta",    "" }, {"UMi", "zeta",     "" }},
		},
		{	// Vela
			{{"Vel", "gamma",   "1"}, {"Vel", "delta",    "" }},
			{{"Vel", "delta",   "" }, {"Vel", "kappa",    "" }},
			{{"Vel", "kappa",   "" }, {"Vel", "phi",      "" }},
			{{"Vel", "phi",     "" }, {"Vel", "mu",       "" }},
			{{"Vel", "mu",      "" }, {"Vel", "psi",      "" }},
			{{"Vel", "psi",     "" }, {"Vel", "lambda",   "" }},
			{{"Vel", "lambda",  "" }, {"Vel", "gamma",    "1"}},
		},
		{	// Virgo
			{{"Vir", "alpha",   "" }, {"Vir", "theta",    "" }},
			{{"Vir", "theta",   "" }, {"Vir", "gamma",    "" }},
			{{"Vir", "gamma",   "" }, {"Vir", "eta",      "" }},
			{{"Vir", "eta",     "" }, {"Vir", "beta",     "" }},
			{{"Vir", "beta",    "" }, {"Vir", "nu",       "" }},
			{{"Vir", "nu",      "" }, {"Vir", "omicron",  "" }},
			{{"Vir", "omicron", "" }, {"Vir", "eta",      "" }},
			{{"Vir", "gamma",   "" }, {"Vir", "delta",    "" }},
			{{"Vir", "delta",   "" }, {"Vir", "epsilon",  "" }},
			{{"Vir", "gamma",   "" }, {"Vir", "zeta",     "" }},
			{{"Vir", "zeta",    "" }, {"Vir", "tau",      "" }},
			{{"Vir", "tau",     "" }, {"Vir", "109",      "" }},
			{{"Vir", "zeta",    "" }, {"Vir", "iota",     "" }},
			{{"Vir", "iota",    "" }, {"Vir", "mu",       "" }},
		},
		{	// Volans
			{{"Vol", "alpha",   "" }, {"Vol", "beta",     "" }},
			{{"Vol", "beta",    "" }, {"Vol", "epsilon",  "" }},
			{{"Vol", "epsilon", "" }, {"Vol", "delta",    "" }},
			{{"Vol", "delta",   "" }, {"Vol", "gamma",    "1"}},
			{{"Vol", "gamma",   "1"}, {"Vol", "epsilon",  "" }},
			{{"Vol", "epsilon", "" }, {"Vol", "alpha",    "" }},
		},
		{	// Vulpecula
			{{"Vul", "alpha",   "" }, {"Vul", "13",       "" }},
		},
	};
	
	public static void main(String[] args) throws IOException 
	{
		String ybsc_path = "//magrathea/dsk/dmpase/home/Astronomy/Catalogs/Yale Bright Star Catalog/BSC5.dat";
		YaleBrightStarAscCatalog ybsc = new YaleBrightStarAscCatalog(ybsc_path);
		System.out.println(ybsc.get("Vir", "109", ""));

		/*/
		for (String[][][] cons: outline) {
			for (String[][] pair: cons) {
				String[] star0 = pair[0];
				String   nam0 = star0[0];
				String   bay0 = YaleBrightStarAscCatalog.get_bayer_tld(star0[1]);
				String   sub0 = star0[2];
	
				String[] star1 = pair[1];
				String   nam1 = star1[0];
				String   bay1 = YaleBrightStarAscCatalog.get_bayer_tld(star1[1]);
				String   sub1 = star1[2];

				System.out.printf("   (%s %s %1s) (%s %s %1s)\n", nam0, bay0, sub0, nam1, bay1, sub1); 
				System.out.println(ybsc.get(nam0, bay0, sub0));
				System.out.println(ybsc.get(nam1, bay1, sub1));
				
				if (star0 == null || star1 == null) {
					System.exit(1);
				}
			}
		}
		/*/
	}
}
